.TH SIMEIS-SERVER 1 "19 juin 2026" "0.2.0" "Simeis"
.SH NAME
simeis-server \- serveur de jeu API pour Simeis
.SH SYNOPSIS
.B simeis-server
.SH DESCRIPTION
Simeis est un jeu par API qui permet de gérer un empire économique dans une galaxie fictive.
Le binaire
.B simeis-server
lance un serveur HTTP local et expose les routes de l'API de jeu.

La documentation complète de l'API est disponible dans le fichier
.B doc/swagger.json
et par l'interface Swagger UI servie sur la racine HTTP.

.SH AUTHOR
Le projet Simeis a été développé par Arthur Millet, Mathéo Souchet, Bryan Metro et Maxime Kiniffo.

