name: Check TODOS

on:
  pull_request:

jobs:
  check-todos:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Vérifier les TODOS
        env:
          GH_TOKEN: ${{ github.token }}
        run: python3 scripts/check_todos.py
