name: Create or update release on release/*

on:
  pull_request:
    branches:
      - release/*
    types:
      - closed

jobs:
  main:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.base.ref, 'release/')
    name: Create/Update Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build release
        run: make release

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Debian packaging tools
        run: |
          sudo apt-get update
          sudo apt-get install -y debhelper dpkg-dev build-essential fakeroot

      - name: Prepare Debian maintainer scripts
        run: chmod +x debian/rules debian/simeis.postinst debian/simeis.prerm

      - name: Build Debian package
        env:
          DEB_BUILD_OPTIONS: nocheck
        run: |
          export PATH="$PATH:/home/runner/.cargo/bin"
          dpkg-buildpackage -us -uc -b -d

      - name: Get version
        run: |
          VERSION=${GITHUB_BASE_REF#release/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create or update GitHub Release
        uses: github/create-update-github-release@v2
        with:
          tag: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: "Release for branch release/${{ env.VERSION }}"
          draft: false
          prerelease: false
          files: |
            target/release/simeis-server
            dist/*.deb
            doc/manual.pdf
            doc/swagger.json
            doc/swagger-ui.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      